version: '3'

secrets:
  openai_api_key:
    environment: "OPEN_AI_API_KEY"

services:
  api:
    image: recipe-api
    env_file:
      - .env
    build:
      context: ./api
      dockerfile: Dockerfile
      target: deploy
    secrets:
      - openai_api_key
    volumes:
      - ./db:/app/db
    ports:
      - "5130:80"
    networks:
      - app-network

  web:
    image: recipe-web
    build:
      context: ./web
      dockerfile: Dockerfile
      target: deploy
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

